CREATE TABLE admin (
id INT PRIMARY KEY AUTO_INCREMENT,
username VARCHAR(50),
password VARCHAR(255),
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ADMIN
username: admin
password: 123456

CREATE TABLE tblRequest (
RequestId INT PRIMARY KEY AUTO_INCREMENT,
Name VARCHAR(255) NOT NULL,
Budget DECIMAL(15,2) NOT NULL,
Purpose TEXT NOT NULL,
DepartmentId INT,
CreatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UpdatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE tblYearlyFunds (
YearlyId INT PRIMARY KEY AUTO_INCREMENT,
Funds DECIMAL(15,2) NOT NULL,
Year YEAR NOT NULL,
DepartmentId INT,
CreatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UpdatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE tblYearlyFunds AUTO_INCREMENT=22222;


CREATE TABLE tblDepartment (
DepartmentId INT PRIMARY KEY AUTO_INCREMENT,
DepartmentName VARCHAR(255) NOT NULL,
CurrentFunds DECIMAL(15,2) NOT NULL,
CreatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UpdatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE tblDepartment AUTO_INCREMENT=44444;